<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hellocode"
 *
 * Auto generated by Extension Builder 2018-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'hellocode distribution',
    'description' => 'FLUID Templates & TypoScript',
    'category' => 'distribution',
    'author' => 'Stefan Sajok',
    'author_email' => 'sajok@hellocode.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
